---
name: moderne-ingest

on:
  push:
    branches: [main]
  workflow_dispatch: {}
  schedule:
    - cron: 0 17 * * *

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://moderne/ingest:java11-latest
        env:
          MODERNE_API_ACCESS_TOKEN: ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
